# Generated by Django 5.1.6 on 2025-03-08 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='storegoods',
            options={'verbose_name_plural': 'Store Goods'},
        ),
    ]
